package io.github.maxsanttos.deletando_recurso_no_servidor.exception;

public class PedidoNaoEncontradoException extends RuntimeException {
    public PedidoNaoEncontradoException() {
        super("Pedido n√£o encontrado.");
    }
}
